title: Marvin Connected Home for Home Assistant
description: Unofficial custom integration for automated windows and skylights
url: https://cb2206.github.io
baseurl: /ha-marvin-connected-home
theme: jekyll-theme-minimal
plugins:
  - jekyll-sitemap
